So the idea is finding the shortest path between two **actors** via a sequence of **movies**

so this is a search problem (BFS) where states are **actors** and actions are **movies**

There are two directories ```small``` and ```large```, indicating the size of the datasets.

In [1]:
import pandas as pd

So we have ID with a name and birthday from the current csv file.
* The **ID** corresponds with their entry in the IMDb database

In [5]:
df_people_small = pd.read_csv('./small/people.csv')
df_people_small.head()

id            name  birth
0   102     Kevin Bacon   1958
1   129      Tom Cruise   1962
2   144      Cary Elwes   1962
3   158       Tom Hanks   1956
4  1597  Mandy Patinkin   1952

In [6]:
len(df_people_small)

16

In [8]:
df_movies_small = pd.read_csv('./small/movies.csv')
df_movies_small.head()

id               title  year
0  112384           Apollo 13  1995
1  104257      A Few Good Men  1992
2  109830        Forrest Gump  1994
3   93779  The Princess Bride  1987
4   95953            Rain Man  1988

In [9]:
len(df_movies_small)

5

The ```stars.csv``` file establishes a relationship between the people in ```people.csv``` and the movies in ```movies.csv```.

* So the first row shows that person with **id** ```102``` (Kevin Bacon) starred in movie **id** ```104257``` (A Few Good Men)

In [10]:
df_stars_small = pd.read_csv('./small/stars.csv')
df_stars_small.head()

person_id  movie_id
0        102    104257
1        102    112384
2        129    104257
3        129     95953
4        144     93779

In [11]:
len(df_stars_small)

20

* ```names``` dictionary to store mappings between celebrity names and IDs
* ```people``` maps each person's id to another dictionary with values for each person's **name**, **birth year** and the set of all **movies** they have starred in.
* ```movies``` dictionary maps each movie's **id** to another dictionary with values for that movie's **title**, **release year**, and the set of all the movie's **stars**

### Names

In [22]:
names = {}

for i in range(len(df_people_small)):
    names[df_people_small.iloc[i]['name']] = df_people_small.iloc[i]['id']

names

{'Kevin Bacon': 102,
 'Tom Cruise': 129,
 'Cary Elwes': 144,
 'Tom Hanks': 158,
 'Mandy Patinkin': 1597,
 'Dustin Hoffman': 163,
 'Chris Sarandon': 1697,
 'Demi Moore': 193,
 'Jack Nicholson': 197,
 'Bill Paxton': 200,
 'Sally Field': 398,
 'Valeria Golino': 420,
 'Gerald R. Molen': 596520,
 'Gary Sinise': 641,
 'Robin Wright': 705,
 'Emma Watson': 914612}

### People

In [ ]:
people = {}

for i in range(len())

## Shortest Path

Return the shortest path from the person with **id** ```source``` to the person with **id** ```target```
* returns a list where each list item is the next ```(movie_id, person_id)``` pair in the path from the source to the target